Adding basic CloudFoundry support
hubotio/hubot-redis-brain pull request #24
Opened 2016-12-15 00:11 UTC by quickjp2

I wanted to be able to use CloudFoundry variables, so I wrote a function to be able to parse through a cf environment to gather the needed parameters for the redis service.

I have tested this script and validated it to work in a running cf instance.

2016-12-20 03:27 UTC, quickjp2 commented
@technicalpickles would you have some time soon to review this?

Thank you!

2016-12-20 04:01 UTC, technicalpickles commented
I'm on paternity leave through the New Year https://github.com/github/hubot/issues/1210

2016-12-20 04:21 UTC, quickjp2 commented
Totally didn't see that, my bad. Congrats and no rush!

2017-04-13 19:02 UTC, quickjp2 commented
@technicalpickles Hope you've had a good leave and subsequent months! Wanted to check in and see what the verdict was, since I have a few more teams at my company wanting to deploy their own hubot in CloudFoundry. 😃 

Thanks!

2017-06-02 22:08 UTC, mose requested changes

2017-06-02 22:08 UTC, mose commented on src/redis-brain.coffee
> +               redisUrlEnv = "CF_REDIS_SERIVCE"
There is a typo here on `CF_REDIS_SERIVCE`

2017-09-16 15:12 UTC, mose approved these changes

2017-09-16 15:21 UTC, mose commented
hmm, I'm afraid the recent move from coffeescript to pure js included some code changes that make this pull request impossible to merge as-is.

2017-10-03 17:31 UTC, quickjp2 commented
@mose It's all good, this was submitted way before the move. If you want, you can close this PR, and I'll submit the changes in pure js in a different PR.

2017-10-03 17:41 UTC, closed without merging